# CMD: docker-compose --file docker-compose.test.yml up --build
version: '3'
services:
  goss:
    image: aelsabbahy/goss
    volumes:
      - goss-executable:/goss
    command: goss --version
  sut:
    build: .
    depends_on:
      - goss
    volumes:
      - .:/project
      - goss-executable:/goss
    command: /goss/goss --gossfile test/goss/goss.yaml validate --format documentation --color
volumes:
  goss-executable:
