#             Builders Execution Commands
# the following configuration commands will be self-contained in the tool
# to provide some known defaults for ease of use and quick start
# However, to create a clear separation between the builder's and the build tool
# the tool will support adding a path to the configuration file
# path property wins respective build commands

# Note: in the future this file will be removed from the tool

# usage: to add new command to the file, execute command `go:generate`
# The command should be executed on the root project level to regenerate the file that contain the binary (see generator.go file)


module-types:
- name: html5
  info: "installing module dependencies & execute grunt & remove dev dependencies"
  path: "path to config file which override the following default commands"
  type:
  - command: npm install
  - command: grunt
  - command: npm prune --production
- name: java
  info: "build java application"
  path: "path to config file which override the following default commands"
  type:
  - command: mvn clean install
- name: nodejs
  info: "build nodejs application"
  path: "path to config file which override the following default commands"
  type:
  - command: npm prune --production